version: "3"
services:
    # mongodb_container:
    #     image: mongo
    #     container_name: mongodb
    #     restart: always
    #     env_file:
    #       - database.env
    #     environment:
    #       # MONGO_INITDB_ROOT_USERNAME: root
    #       # MONGO_INITDB_ROOT_PASSWORD: rootpassword
    #     ports:
    #       - 27017:27017
    #     volumes:
    #       # need for saving db data
    #       #- mongodb_data_container:/data/db
    investigation_server:
        build: ./intestigation_server
        container_name: server
        restart: always
        # command npm run start
        # links: 
        #   - mongodb_container # after run mongodb_container
        ports:
          - 8000:8000
        # TODO ask
        # networks: where it used
        # stdin_open: true # work on project outside container
        # tty: true # work on project inside container
        env_file: database.env
        # depends_on: mongodb_container
volumes:
    mongodb_data_container:
